### ISSUE TITLE
500 TypeError: this.fail is not a function

### ISSUE THREAD

**Issue by pcg-codes** [passport/discuss#28]
I've build a basic loopback4 application with authentication via passport-http module like described in this [https://github.com/strongloop/loopback-next/tree/master/packages/authentication#loopbackauthentication](url) documentation. 
For each request with auth i receive the following error: 

> Unhandled error in GET /whoami: 500 TypeError: this.fail is not a function
    at BasicStrategy.authenticate (/home/node/app/node_modules/passport-http/lib/passport-http/strategies/basic.js:69:37)
    at AuthenticateActionProvider.action (/home/node/app/node_modules/@loopback/authentication/dist/providers/auth-action.provider.js:55:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Tried to investigate the code but couldn't figure out where this function should come from.
Any hints on this ?

**Comment by byAhmadAli** [comment]
+1!
